# Combine Raw Data
Combines all 17 xlsx files from the `Raw Data` folder into a single DataFrame.

In [64]:
import pandas as pd
import os

In [65]:
RAW_DATA_DIR = "Raw Data"

xlsx_files = sorted([f for f in os.listdir(RAW_DATA_DIR) if f.endswith(".xlsx")])
print(f"Found {len(xlsx_files)} files:")
for f in xlsx_files:
    print(f"  {f}")

Found 17 files:
  Basemetal.xlsx
  Coal.xlsx
  CornCommodityCTM.xlsx
  CrudeOil.xlsx
  Electricity.xlsx
  Emmissions.xlsx
  FibersCommodityCTM.xlsx
  FoodstuffCTM.xlsx
  Livestock.xlsx
  NaturalGas.xlsx
  OtherGrain.xlsx
  Shipping.xlsx
  Soy.xlsx
  Weather.xlsx
  Wheat.xlsx
  industrialmetal.xlsx
  preciousmetal.xlsx

In [66]:
dfs = []

for filename in xlsx_files:
    filepath = os.path.join(RAW_DATA_DIR, filename)
    df = pd.read_excel(filepath, sheet_name=0)
    # Drop rows where Ticker is null (blank separator rows)
    df = df.dropna(subset=["Ticker"])
    # Add a source column to track which file each row came from
    df["Source"] = os.path.splitext(filename)[0]
    dfs.append(df)
    print(f"{filename}: {len(df)} rows")

combined = pd.concat(dfs, ignore_index=True)
print(f"\nTotal rows: {len(combined)}")

Basemetal.xlsx: 439 rows
Coal.xlsx: 85 rows
CornCommodityCTM.xlsx: 87 rows
CrudeOil.xlsx: 979 rows
Electricity.xlsx: 3849 rows
Emmissions.xlsx: 219 rows
FibersCommodityCTM.xlsx: 24 rows
FoodstuffCTM.xlsx: 178 rows
Livestock.xlsx: 25 rows
NaturalGas.xlsx: 1174 rows
OtherGrain.xlsx: 161 rows
Shipping.xlsx: 543 rows
Soy.xlsx: 146 rows
Weather.xlsx: 112 rows
Wheat.xlsx: 206 rows
industrialmetal.xlsx: 158 rows
preciousmetal.xlsx: 345 rows

Total rows: 8730

In [67]:
combined.head(10)

,Ticker,Description,Exchange,Type,Options,Volume,Open Interest,Source
0,XCPA Comdty,USD/Tonne Copper Futures Contracts,Borsa Istanbul :IST,Future,No,10.0,279.0,Basemetal
1,ALAA Comdty,Alumina FOB Australia (Platts) Futures,COMEX division of NYMEX ...,Future,No,300.0,2470.0,Basemetal
2,ALEA Comdty,Aluminum,COMEX division of NYMEX ...,Future,Yes,1931.0,2549.0,Basemetal
3,AUPA Comdty,Aluminum MW US Trans Prem Swap,COMEX division of NYMEX ...,Future,Yes,434.0,25687.0,Basemetal
4,CUPA Comdty,Copper Premium Grade A CIF Shanghai (Metal Bul...,COMEX division of NYMEX ...,Future,No,0.0,0.0,Basemetal
5,CVTA Comdty,Cobalt Metal (Fastmarkets) Futures,COMEX division of NYMEX ...,Future,Yes,144.0,14133.0,Basemetal
6,FALA Comdty,Alumina FOB Australia (Metal Bulletin) Futures,COMEX division of NYMEX ...,Future,No,0.0,0.0,Basemetal
7,FSAA Comdty,"HMS 80/20 Ferrous Scrap, CFR Turkey Swap Futures",COMEX division of NYMEX ...,Future,Yes,0.0,10.0,Basemetal
8,HDSA Comdty,U.S. Midwest Domestic Steel Premium (CRU) Futures,COMEX division of NYMEX ...,Future,No,90.0,375.0,Basemetal
9,HERA Comdty,North European Hot-Rolled Coil Steel (Argus) F...,COMEX division of NYMEX ...,Future,Yes,922.0,9365.0,Basemetal

In [68]:
combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8730 entries, 0 to 8729
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ticker         8730 non-null   object
 1   Description    8686 non-null   object
 2   Exchange       8730 non-null   object
 3   Type           8730 non-null   object
 4   Options        8730 non-null   object
 5   Volume         8730 non-null   float64
 6   Open Interest  8730 non-null   float64
 7   Source         8730 non-null   object
dtypes: float64(2), object(6)
memory usage: 545.8+ KB

In [69]:
futures = combined[combined["Type"] == "Future"].reset_index(drop=True)
print(f"Futures rows: {len(futures)}")

Futures rows: 2825

In [70]:
futures.head(10)

,Ticker,Description,Exchange,Type,Options,Volume,Open Interest,Source
0,XCPA Comdty,USD/Tonne Copper Futures Contracts,Borsa Istanbul :IST,Future,No,10.0,279.0,Basemetal
1,ALAA Comdty,Alumina FOB Australia (Platts) Futures,COMEX division of NYMEX ...,Future,No,300.0,2470.0,Basemetal
2,ALEA Comdty,Aluminum,COMEX division of NYMEX ...,Future,Yes,1931.0,2549.0,Basemetal
3,AUPA Comdty,Aluminum MW US Trans Prem Swap,COMEX division of NYMEX ...,Future,Yes,434.0,25687.0,Basemetal
4,CUPA Comdty,Copper Premium Grade A CIF Shanghai (Metal Bul...,COMEX division of NYMEX ...,Future,No,0.0,0.0,Basemetal
5,CVTA Comdty,Cobalt Metal (Fastmarkets) Futures,COMEX division of NYMEX ...,Future,Yes,144.0,14133.0,Basemetal
6,FALA Comdty,Alumina FOB Australia (Metal Bulletin) Futures,COMEX division of NYMEX ...,Future,No,0.0,0.0,Basemetal
7,FSAA Comdty,"HMS 80/20 Ferrous Scrap, CFR Turkey Swap Futures",COMEX division of NYMEX ...,Future,Yes,0.0,10.0,Basemetal
8,HDSA Comdty,U.S. Midwest Domestic Steel Premium (CRU) Futures,COMEX division of NYMEX ...,Future,No,90.0,375.0,Basemetal
9,HERA Comdty,North European Hot-Rolled Coil Steel (Argus) F...,COMEX division of NYMEX ...,Future,Yes,922.0,9365.0,Basemetal

In [71]:
futures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2825 entries, 0 to 2824
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ticker         2825 non-null   object
 1   Description    2825 non-null   object
 2   Exchange       2825 non-null   object
 3   Type           2825 non-null   object
 4   Options        2825 non-null   object
 5   Volume         2825 non-null   float64
 6   Open Interest  2825 non-null   float64
 7   Source         2825 non-null   object
dtypes: float64(2), object(6)
memory usage: 176.7+ KB

In [72]:
futures_active = futures[
    (futures["Volume"] > 1000) | (futures["Open Interest"] > 1000)
].reset_index(drop=True)
print(f"Futures with Volume or Open Interest > 1000: {len(futures_active)} rows")

Futures with Volume or Open Interest > 1000: 435 rows

In [73]:
futures_active.head(10)

,Ticker,Description,Exchange,Type,Options,Volume,Open Interest,Source
0,ALAA Comdty,Alumina FOB Australia (Platts) Futures,COMEX division of NYMEX ...,Future,No,300.0,2470.0,Basemetal
1,ALEA Comdty,Aluminum,COMEX division of NYMEX ...,Future,Yes,1931.0,2549.0,Basemetal
2,AUPA Comdty,Aluminum MW US Trans Prem Swap,COMEX division of NYMEX ...,Future,Yes,434.0,25687.0,Basemetal
3,CVTA Comdty,Cobalt Metal (Fastmarkets) Futures,COMEX division of NYMEX ...,Future,Yes,144.0,14133.0,Basemetal
4,HERA Comdty,North European Hot-Rolled Coil Steel (Argus) F...,COMEX division of NYMEX ...,Future,Yes,922.0,9365.0,Basemetal
5,HGA Comdty,Copper,COMEX division of NYMEX ...,Future,Yes,106997.0,273789.0,Basemetal
6,HGAA Comdty,Copper Financial Futures,COMEX division of NYMEX ...,Future,Yes,19.0,6716.0,Basemetal
7,HRCA Comdty,"Steel, Hot-Rolled Coil",COMEX division of NYMEX ...,Future,Yes,1588.0,40910.0,Basemetal
8,LFAA Comdty,Lithium Hydroxide CIF CJK (Fastmarkets) Futures,COMEX division of NYMEX ...,Future,Yes,203.0,15521.0,Basemetal
9,LJCA Comdty,Lithium Carbonate CIF CJK (Fastmarkets) Futures,COMEX division of NYMEX ...,Future,No,30.0,5221.0,Basemetal

In [74]:
futures_active.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Ticker         435 non-null    object
 1   Description    435 non-null    object
 2   Exchange       435 non-null    object
 3   Type           435 non-null    object
 4   Options        435 non-null    object
 5   Volume         435 non-null    float64
 6   Open Interest  435 non-null    float64
 7   Source         435 non-null    object
dtypes: float64(2), object(6)
memory usage: 27.3+ KB

In [75]:
futures_active["Source"].value_counts()

Electricity           100
Basemetal              50
preciousmetal          43
NaturalGas             41
FoodstuffCTM           36
CrudeOil               34
industrialmetal        34
Soy                    19
CornCommodityCTM       15
OtherGrain             13
Wheat                  13
Shipping               11
Coal                    7
Livestock               7
FibersCommodityCTM      5
Weather                 4
Emmissions              3
Name: Source, dtype: int64

In [76]:
output_path = "futures_raw_data.xlsx"
futures_active.to_excel(output_path, index=False)
print(f"Saved to {output_path}")

Saved to futures_raw_data.xlsx